name: numerizer
description: Mobile application for document numerization.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  # imported flutter packages
  http: ^0.13.3
  camera: ^0.8.1+5
  path: ^1.8.0
  path_provider: ^2.0.2
  image_picker: ^0.8.2
  async: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  #image_path: "img/logo/TechFoodIcon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # moon icons
     - assets/img/moonIcon.png
     - assets/img/outlinedMoonIcon.png
    # sun icons
     - assets/img/sunIcon.png
     - assets/img/outlinedSunIcon.png
    # heart icons
     - assets/img/heartIcon.png
     - assets/img/outlinedHeartIcon.png
     - assets/img/brokenHeartIcon.png
     # emoji icons
     - assets/img/unhappyEmojiIcon.png
     - assets/img/outlinedUnhappyEmojiIcon.png
    # doc icons
     - assets/img/editDocIcon.png
     - assets/img/excelDocIcon.png
     - assets/img/wordDocIcon.png
    # other icons
     - assets/img/lampIcon.png
     - assets/img/previousIcon.png
     - assets/img/searchIcon.png
     - assets/img/settingsIcon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
         - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
           weight: 700
         - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
           weight: 800
         - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
           weight: 900
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
